image: docker

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build-frontend:
  stage: build
  script:
    - cd frontend
    - docker build -t frontend .