image: docker

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build-frontend:
  stage: build
  before_script:
    - echo "Rodando frontend"
  script:
    - cd frontend
    - docker build -t frontend .
    - echo "Subindo front"
    - docker push "$CI_REGISTRY_IMAGE_FRONT"
  after_script:
    - echo "Frontend OK"

build-backend:
  stage: build
  before_script:
    - echo "Rodando backend"
  script:
    - cd backend
    - docker build -t backend .
    - echo "subindo back"
    - docker push "$CI_REGISTRY_IMAGE_BACK"
  after_script:
    - echo "Backend OK"    

test-frontend:
  image: docker/compose
  stage: test
  before_script:
    - echo "Rodando testes front"
  script:
    - docker-compose run --entrypoint "npm run test" frontend
  after_script:
    - echo "Testes frontend OK"
    
test-backend:
  image: docker/compose
  stage: test
  before_script:
    - echo "Rodando testes back"
  script:
    - docker-compose run --entrypoint "npm run unittest" backend
  after_script:
    - echo "Testes backend OK"    