image: docker

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build-frontend:
  stage: build
  before_script:
    - echo "Rodando frontend"
  script:
    - cd frontend
    - docker build -t frontend .
  after_script:
    - echo "Frontend OK"

build-backend:
  stage: build
  before_script:
    - echo "Rodando backend"
  script:
    - cd backend
    - docker build -t backend .
  after_script:
    - echo "Backend OK"    